import React from 'react';
import { X, ShieldCheck } from 'lucide-react';

export function TwoFactorSetupModal({
  setupData,
  token,
  onTokenChange,
  backupCodes,
  enabling,
  onSubmit,
  onClose,
}: {
  setupData: any;
  token: string;
  onTokenChange: (v: string) => void;
  backupCodes: string[];
  enabling: boolean;
  onSubmit: (e: React.FormEvent) => void;
  onClose: () => void;
}) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 backdrop-blur-xs p-4">
      <div className="bg-white dark:bg-slate-900 border p-6 rounded-3xl w-full max-w-md space-y-5 shadow-2xl relative animate-in fade-in duration-200">
        <button onClick={onClose} aria-label="Close" className="absolute right-4 top-4 text-slate-550 hover:bg-slate-100 dark:hover:bg-slate-800 p-1 rounded-lg">
          <X className="h-5 w-5" />
        </button>

        <div className="space-y-1">
          <h3 className="font-bold text-base">Setup Authenticator App</h3>
          <p className="text-xs text-slate-400">Follow these steps to activate 2FA protection.</p>
        </div>

        {backupCodes.length > 0 ? (
          <div className="space-y-4">
            <div className="bg-emerald-500/10 border border-emerald-500/20 p-3 rounded-xl flex items-center space-x-2 text-emerald-500">
              <ShieldCheck className="h-5 w-5" />
              <span className="text-[10px] font-black uppercase">✓ 2FA Activated Successfully</span>
            </div>
            <p className="text-xs text-slate-550 dark:text-slate-400 leading-normal">
              Save these backup codes in a safe place. If you ever lose your authenticator device, you can use these to recover access:
            </p>
            <div className="grid grid-cols-2 gap-2 bg-slate-50 dark:bg-slate-800 p-3 rounded-xl font-mono text-center text-xs font-bold border">
              {backupCodes.map((code) => (
                <span key={code} className="select-all">
                  {code}
                </span>
              ))}
            </div>
            <button onClick={onClose} className="w-full py-2.5 bg-primary text-white rounded-xl font-bold">
              Finish Setup
            </button>
          </div>
        ) : (
          <form onSubmit={onSubmit} className="space-y-4 text-xs font-semibold leading-normal">
            <div className="space-y-3">
              <p className="text-slate-550 dark:text-slate-400">
                1. Scan the QR code below using your authenticator app (Google Authenticator, Authy, etc.):
              </p>
              <div className="bg-slate-50 dark:bg-slate-950 p-4 border rounded-2xl flex justify-center">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={setupData.qrCodeUrl} alt="2FA QR Code" className="h-44 w-44 rounded-lg bg-white p-1" />
              </div>
              <p className="text-slate-550 dark:text-slate-400">2. If you cannot scan the code, enter this key manually:</p>
              <div className="p-2 border rounded-xl bg-slate-50 dark:bg-slate-800 font-mono text-center select-all">{setupData.secret}</div>
              <p className="text-slate-550 dark:text-slate-400">3. Enter the 6-digit verification code generated by the app:</p>
              <input
                type="text"
                required
                maxLength={6}
                placeholder="e.g. 123456"
                value={token}
                onChange={(e) => onTokenChange(e.target.value)}
                className="w-full px-4 py-2.5 rounded-xl border bg-slate-50 dark:bg-slate-800 focus:outline-none text-center font-mono text-base tracking-widest"
              />
            </div>

            <button type="submit" disabled={enabling} className="w-full py-2.5 bg-primary text-white rounded-xl font-bold shadow disabled:opacity-50">
              {enabling ? 'Verifying...' : 'Verify and Enable'}
            </button>
          </form>
        )}
      </div>
    </div>
  );
}
